version: "3.3"

services:
    gamepad-extensions:
        image: nginx
        ports:
            - 8082:80
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html:ro
            - ./js:/usr/share/nginx/html/js:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ../gamepad-viewer:/usr/share/nginx/html/gamepad-viewer:ro
